### ISSUE TITLE
Forum

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-dsm-app#10]
Users are observers to a single chat.

- [ ] startGroupChatManager on the correct place
- [x] drawer menu entry
- [x] display messages
- [x] write and send message
- [x] handle new messages
- [ ] get info from hyperty url
- [ ] user tokens

[Updated mockup](https://user-images.githubusercontent.com/40800383/45549114-884bd180-b81e-11e8-8b4a-2049571d2eda.png)

**Comment by Felgueiras** [comment]
![sharinglisboa_forum_users](https://user-images.githubusercontent.com/7281851/45206055-f5d68b80-b27b-11e8-900f-33da641d3ac0.png)
![sharinglisboa_forum_timeline](https://user-images.githubusercontent.com/7281851/45206056-f5d68b80-b27b-11e8-836f-6eb9667e4573.png)

**Comment by patriciagaspar** [comment]
![sharinglisboa_forum_timeline](https://user-images.githubusercontent.com/40800383/45549114-884bd180-b81e-11e8-8b4a-2049571d2eda.png)
![sharinglisboa_forum_users](https://user-images.githubusercontent.com/40800383/45549123-90a40c80-b81e-11e8-89b6-a63807721250.png)

**Comment by Felgueiras** [comment]
@pchainho when should GroupChatManager be started? Only when selecting Forum or at the initial hyperties loading?
