### ISSUE TITLE
GIRA Authorisation

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-dsm-app#105]
Open Window Modal with the following content: 

- [x] If GFIT is [disabled](https://user-images.githubusercontent.com/7281851/45367003-213cdb80-b5d8-11e8-962a-7ce7bd5357f2.png) "Para ganhar pontos com a bicicleta GIRA verifique que tem a Aplicação GFIT instalada e dê a sua autorização aqui (chamar função para dar autorização no GFIT)."

- [x]  If GFIT is [enabled ](https://user-images.githubusercontent.com/7281851/45367024-2ef26100-b5d8-11e8-89ff-e6b90e05cccc.png)"Parabéns, a partir de agora vai ganhar pontos com as bicicletas GIRA"

- [x] UI feedback @patriciagaspar

**Comment by patriciagaspar** [comment]
Mockups

![sharinglisboa_settings_gfit_authorization](https://user-images.githubusercontent.com/40800383/45775238-ff320180-bc46-11e8-863d-400a1d3c4f07.png)
![sharinglisboa_settings_start_gira](https://user-images.githubusercontent.com/40800383/45775242-078a3c80-bc47-11e8-9384-1f7fc443a73c.png)
