### ISSUE TITLE
Cache storage size too big

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-dsm-app#129]
Currently above 70M, this is caused by [opaque requests being cached](https://stackoverflow.com/questions/49295113/chrome-shows-high-cache-storage-use/49318583#49318583). To solve this images could be stored on our server.

**Comment by patriciagaspar** [comment]
The assets folder has less than 4M. I would suggest to change the shops avatars for a generic svg image just to see if this solves the problem.
