### ISSUE TITLE
Cause Challenge details

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-dsm-app#13]
- [x] get cause activities from backend

- [x] highlight selected cause (Badge with check as badgeContent https://material-ui.com/demos/badges/)

- [x] display remaining challenge days

- [x] causes icons

- [x] fix table

- [x] bounding box around section

- [x] background width: causeTokens/challengeTokens

- [x] test in Storybook

**Comment by Felgueiras** [comment]
- [ ] get cause activities (Redux)

**Comment by Felgueiras** [comment]
For the icon use an Avatar, if selected cause use badge.
Text is normal text.
