### ISSUE TITLE
"Sumario" and "Escola" details: don't use transactions data

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-dsm-app#137]
To minimise the size of the data transferred from the backend and stored locally as well as calculation performed locally, the number of transactions provided by the backend is limited.

This means data to be used in "Sumario" and "Escolas" screens will not be calculated from the transactions but from a new class: Accounts. Check [here](https://github.com/reTHINK-project/specs/tree/master/datamodel/data-objects/wallet)

**Comment by pchainho** [comment]
Depends on https://github.com/reTHINK-project/dev-java-hyperty/issues/47

**Comment by Felgueiras** [comment]
solved in `accounts` branch
