### ISSUE TITLE
Checkin

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-dsm-app#17]
- [x] disable check-in button if check-in already ocurred during current day
- [x] distance to shop appears in CheckinDialog

- [x] check-in not permitted: show text instead of Button

- [x] clicking bonus info links to bonus view (inside checkin-dialog)

- [x] bonus view inside CheckinDialog (use react-slick)

- [x] checkins: integrate https://material-ui.com/demos/progress/#interactive-integration to give feedback that checkin is taking place
- [x] checkins: display only valid checkins in table

- [x] clicking shop shows shop location

- [x] FeedbackDialog: message for valid checkin (points earned)

- [x] check-in is made using LocationReporterDSM hyperty js

- [x] show user's current position on map

- [x] display snackbar with success/insuccess message

- [x] visual feedback (waiting & result)

**Comment by Felgueiras** [comment]
check-in is made using LocationReporterDSM hyperty js

**Comment by Felgueiras** [comment]
still having issues with detecting wallet change in CheckinDialog to check if new transaction was added
