### ISSUE TITLE
Bonus

### ISSUE THREAD

**Issue by Felgueiras** [reTHINK-project/dev-dsm-app#29]
- [x] display each reward with "link" to map
- [x] fetch from Hyperty
- [x] search by name

- [x] sort by cheapest/closest (reuse QuizzesList login)

- [x] store info in Redux (dummy)

- [x] display number of available rewards in drawer

- [x] sort by cost: show cost

- [x] sort by distance: show distance

**Comment by pchainho** [comment]
To clarify the backend implementation
