### ISSUE TITLE
Styling changes

### ISSUE THREAD

**Issue by Felgueiras** [reTHINK-project/dev-dsm-app#48]
- [ ] Mudar cabeçalho:
![capture](https://user-images.githubusercontent.com/7281851/42227241-f4d32d3c-7ed8-11e8-80d8-102042d8b09b.PNG)
`element.style {
    font-size: 24px;
    font-weight: bold;
}
`
- [ ] Mudar cabeçalho 2:
![capture](https://user-images.githubusercontent.com/7281851/42227241-f4d32d3c-7ed8-11e8-80d8-102042d8b09b.PNG)
`element.style {
    font-size: 24px;
    font-weight: bold;
}
`

**Comment by patriciagaspar** [comment]
alteração de css:
...
