### ISSUE TITLE
Authorization popups are blank in Android

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-dsm-app#62]
- [x] GFIT auth popup is opened blank
![image 1](https://user-images.githubusercontent.com/3893553/43014003-ab56200c-8c42-11e8-810f-d64cc5e3db3c.png)

![screenshot_20180720-172313](https://user-images.githubusercontent.com/3893553/43013992-a1ee76f4-8c42-11e8-8228-f65b79209b16.png)

- [x] Login popup is also opened blank the 2nd time

Discovered a workaround by requesting to open the about:blanck window in chrome, and opening again the popup

**Comment by pchainho** [comment]
It only happens when using an installed App, not in the browser.

**Comment by pchainho** [comment]
One hint: https://stackoverflow.com/questions/46487112/chrome-61-avoid-pwa-opening-blank-links-in-custom-tab

It seems the blanck window has to be opened as new chrome window.

Check why it works login popup but not with auth popup

**Comment by pchainho** [comment]
Seems to be this bug:

https://bugs.chromium.org/p/chromium/issues/detail?id=771418

https://bugs.chromium.org/p/chromium/issues/detail?id=771418#c100

**Comment by pchainho** [comment]
68 was just released  https://chromereleases.googleblog.com/2018/07/chrome-for-android-update.html

**Comment by pchainho** [comment]
After installing version 68 the issue is still there but only when the configuration is done during the initial configuration phase. After the setup is done it works.

**Comment by Felgueiras** [comment]
added a wait() of 1 second before the popup is redirected to the respective URL
