### ISSUE TITLE
Location is continuously collected when not required 

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-dsm-app#63]
Location is continuously collected from device sensors even when not required i..e in screens where location is not required or when the App is not the focus.

Example during setup:
![image](https://user-images.githubusercontent.com/3893553/43013836-1652710e-8c42-11e8-81c5-9cba9dc168cc.png)

**Comment by Felgueiras** [comment]
Setup: after login, location reporter is started, calling `[initPosition()](https://github.com/reTHINK-project/dev-hyperty/blob/develop/src/location/LocationReporter.hy.js#L158)`,

**Comment by Felgueiras** [comment]
ShopsMap is being "rendered" x2 (?)
