### ISSUE TITLE
App uninstalled: reset redux

### ISSUE THREAD

**Issue by Felgueiras** [reTHINK-project/dev-dsm-app#75]
Some useful insights:
- https://github.com/w3c/manifest/issues/636

- https://github.com/w3c/manifest/issues/161

**Comment by Felgueiras** [comment]
for Android: check how long Chrome "waits" before clearing the App data (is this done?)

**Comment by pchainho** [comment]
In case no data is deleted, re-installation should be just a resume and everything should work fine. Test again.
