### ISSUE TITLE
Reset account screen

### ISSUE THREAD

**Issue by Felgueiras** [reTHINK-project/dev-dsm-app#79]
Currently there is a simple [screen ](https://sharing-lisboa.netlify.com/?selectedKind=Reset%20App&selectedStory=reset&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook-addon-viewport%2Faddon-panel)show to the user, with a button that redirects to the Splash Screen.

The button should:

- redirect to splash screen
**or**
- close the app

- [x] layout

**Comment by patriciagaspar** [comment]
![sharinglisboa_profile_remove_data](https://user-images.githubusercontent.com/40800383/44596647-e3ad1580-a7c4-11e8-8eed-f097277f55da.png)
![login_after_deleted account](https://user-images.githubusercontent.com/40800383/44596654-ef004100-a7c4-11e8-9aec-b12fb7a3c3ab.png)
