### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-dsm-app#8]
- [x] bottom navigation: badges with "notification" about new content
http://www.material-ui.com/#/components/bottom-navigation
http://www.material-ui.com/#/components/badge
- [x] bottom navigation: custom icons
- [x] Drawer 'bónus' - show indicator with number of bonus
- [x] quizzes and check-ins added to user's activities

**Comment by Felgueiras** [comment]
- [ ] show badges with "notification" about new content

- [ ] display cause challenge details by school (accordion)

- [ ] "my impact" section
