### ISSUE TITLE
Quiz

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-dsm-app#9]
- [x] question (question text, choices/true or false, answer explanation)

- [x] handle next question button (enable/disable)

- [x] after selecting answer, do not allow to select other one

- [x] quiz name in appbar

- [x] next question: align to bottom

- [x] display amount of tokens won with quiz (end dialog - read from wallet transactions)

- [x] show quiz hint after answering question (dialog)

**Comment by Felgueiras** [comment]
- Initial screen:

- [ ] group quizzes by category
